############################################
# boonstra@netapp.com / 2019
# global/private vars are in vars.yml
# playbook specific vars are down below
#############################################
---
- hosts: localhost
  gather_facts: false
  vars_files:
   vars.yml
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  name: Onboard SVM
  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: present
      name: "{{ vserver }}"
      root_volume: "{{ vserver}}_root"
      root_volume_aggregate: "{{ aggrname }}"
      root_volume_security_style: unix
      <<: *login
  - name: Create interface NFS
    na_ontap_interface:
      state: present
      interface_name: "{{ vserver }}_nfs_data_1"
      home_port: e0c
      home_node: kubOntap97-01
      role: data
      protocols: nfs
      admin_status: up
      failover_policy: local-only
      firewall_policy: data
      is_auto_revert: true
      address: "{{ address_nfs }}"
      netmask: 255.255.255.0
      vserver: "{{ vserver }}"
      <<: *login
  - name: change nfs status
    na_ontap_nfs:
      state: present
      service_state: started
      vserver: "{{ vserver }}"
      nfsv3: enabled
      nfsv4: disabled
      nfsv41: disabled
      tcp: enabled
      udp: enabled
      vstorage_state: disabled
      <<: *login
