############################################
# boonstra@netapp.com / 2021
# global/private vars are in vars.yml
# playbook specific vars are down below
#############################################
---
- hosts: localhost
  collections:
    - netapp.ontap
    - netapp.um_info
  gather_facts: false
  vars_files:
   vars.yml
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: “{{ ansible_env.ANSIBLE_NET_USERNAME }}”
      password: “{{ ansible_env.ANSIBLE_NET_PASSWORD }}”
      https: true
      validate_certs: false
  tasks:
  - name: Get facts
    na_ontap_gather_facts:
       <<: *login
#      hostname: "{{ netapp_hostname }}"
#      username: "{{ netapp_username }}"
#      password: "{{ netapp_password }}"
  - debug:
      var: ontap_facts 
