############################################
# boonstra@netapp.com / 2021
# global/private vars are in vars.yml
# playbook specific vars are down below
#############################################
---
- hosts: localhost
  collections:
    - netapp.ontap
    - netapp.um_info
  gather_facts: false
  vars_files:
   vars.yml
  vars:
    login: &login
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
  tasks:
  - name: Create Policy
    na_ontap_export_policy:
      state: "{{ state }}"
      name: "{{ comment }}"
      vserver: "{{ vserver }}"
      <<: *login
  - name: Create volume 
    na_ontap_volume:
      state: "{{ state }}"
      name: "vol{{ comment }}"
      aggregate_name: "{{ aggrname }}"
      size: "{{ new_size }}"
      size_unit: gb
      policy: "{{ comment }}"
      junction_path: "/vol{{ comment }}"
      space_guarantee: "none"
      volume_security_style: unix
      comment: "{{ comment }}"
      vserver: "{{ vserver }}"
      <<: *login
  - name: Setup rules
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: "{{ comment }}"
      vserver: "{{ vserver }}"
      client_match: "{{ client_match }}"
      ro_rule: "{{ ro_rule }}"
      rw_rule: "{{ rw_rule }}"
      super_user_security: "{{ super_user_security }}"
      <<: *login
